- alias: 00_start
  initial_state: true
  trigger:
  - platform: homeassistant
    event: start
  action:  
    - service: mqtt.publish
      data_template:
         topic: "notification/info"
         payload_template: '011'
         retain: true
    - delay: 00:01:10
    - service: mqtt.publish
      data_template:
         topic: "notification/info"
         payload_template: '012'

- alias: 00_backup_everyday
  initial_state: true
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    - service: recorder.purge
      data:
          keep_days: 1
          repack: true


