- alias: 05_gg_heater
  id: 'Режим обогрева в гостиной'
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      minutes: '/5'
    - platform: state
      entity_id:
        - binary_sensor.living_heat
  action:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {%- if states.binary_sensor.living_heat.state == 'on' -%}
          script.living_home
          {%- elif states.binary_sensor.living_heat.state == 'off' -%}
          script.living_away
          {%- endif -%}  

## Включение увлажнителя и очистителя  
- alias: 05_gg_hum_auto
  id: 'Увлажнение в гостиной'
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id:
        - input_number.humidity_level_gg
        - sensor.05_mean_humidity
        - binary_sensor.living_hum
  action:
    service_template: >-
      {% set hi = (states('input_number.humidity_level_gg') | float) + 5 %}
      {% set lo = (states('input_number.humidity_level_gg') | float) - 5 %}
      {% set humidity = states('sensor.05_mean_humidity') | float %}
      {% if humidity > hi %}
        switch.turn_off
      {% elif states.binary_sensor.living_hum.state == 'off' %} 
        switch.turn_off
      {% elif humidity < lo and states.binary_sensor.living_hum.state == 'on' %}
        switch.turn_on
      {% else %}
        switch.turn_{{states('switch.gg_humidifier') | lower}}
      {% endif %}
    entity_id: switch.gg_humidifier