- alias: 07_dd_hum_auto
  id: 'Увлажнение в детской Д'
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - input_number.humidity_level_dd
      - sensor.07_mean_humidity
      - binary_sensor.dd_hum
  action:
    service_template: >-
      {% set hi = (states('input_number.humidity_level_dd') | float) + 5 %}
      {% set lo = (states('input_number.humidity_level_dd') | float) - 5 %}
      {% set humidity = states('sensor.07_mean_humidity') | float %}
      {% if humidity > hi %}
        switch.turn_off
      {% elif states.binary_sensor.dd_hum.state == 'off' %} 
        switch.turn_off
      {% elif humidity < lo and states.binary_sensor.dd_hum.state == 'on' %}
        switch.turn_on
      {% else %}
        switch.turn_{{states('switch.plug_158d000114a1e1') | lower}}
      {% endif %}
    entity_id: switch.plug_158d000114a1e1
    
## Предупреждение о недостатке воды
- alias: 07_dd_hum_water_warning
  initial_state: true
#   initial_state: false
  trigger:
## Падение мощности менее 10 Ватт
   - platform: numeric_state
     entity_id: sensor.load_158d000114a1e1
     below: 10
     for:
       minutes: 1
  condition:
## Увлажнитель включен
     - condition: state
       entity_id: switch.plug_158d000114a1e1
       state: 'on'
## Время работы
     - condition: state
       entity_id: binary_sensor.day_work
       state: 'on'
  action:
    - service: mqtt.publish
      data_template:
        topic: "notification/messages"
        payload_template: '0700'
        retain: true
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 28:6C:07:F0:AD:27
        ringtone_id: 10011
        ringtone_vol: 50