# - alias: 911_backup_timer
#   initial_state: true
#   trigger:
#   - platform: state
#     entity_id:
#       - sensor.reserve_live_ping
#   action:
#   - service: timer.start
#     entity_id: timer.backup
#     data: 
#       duration: 00:02:00

- alias: 911_reserve_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.reserve_state
   to: 'unavailable'
  action:
    - service: mqtt.publish
      data_template:
         topic: "notification/error"
         payload_template: '021'

- alias: 911_reserve_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.reserve_state
   from: 'unavailable'
  action:
    - service: mqtt.publish
      data_template:
         topic: "notification/error"
         payload_template: '022'

- alias: 911_scenario_on
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.reserve_scenario_group
   to: 'unavailable'
  condition:
    - condition: state
      entity_id: group.scenario
      state: 'off'     
  action:
    - service: homeassistant.turn_on
      entity_id:
         - group.scenario

- alias: 911_mqtt_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.mqtt_state
   to: 'unavailable'
  action:
    - service: notify.telegram
      data:
        message: "Потеря связи с MQTT сервером, Khadas VIM 2 - {{ states('sensor.time_date') }} ."

- alias: 911_mqtt_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.mqtt_state
   from: 'unavailable'
  action:
    - service: notify.telegram
      data:
        message: "Связь с MQTT сервером, Khadas VIM 2 восстановлена в - {{ states('sensor.time_date') }} ."
        
- alias: 911_rasp3_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.rasp3b_state
   to: 'unavailable'
  action:
    - service: mqtt.publish
      data_template:
         topic: "notification/error"
         payload_template: '031' 

- alias: 911_rasp3_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.rasp3b_state
   from: 'unavailable'
  action:
    - service: mqtt.publish
      data_template:
         topic: "notification/error"
         payload_template: '032'
         
- alias: 911_test_lost
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.test_state
   to: 'unavailable'
  action:
    - service: mqtt.publish
      data_template:
         topic: "notification/error"
         payload_template: '041' 

- alias: 911_test_online
  initial_state: true
  trigger:
   platform: state
   entity_id: sensor.test_state
   from: 'unavailable'
  action:
    - service: mqtt.publish
      data_template:
         topic: "notification/error"
         payload_template: '042'